### ISSUE TITLE
Folder bookmarks broken on latest Vim

### ISSUE THREAD

**Issue by amadeus** [mhinz/vim-startify#220]
As the title states, it appears that folder bookmarks no longer properly work. When a folder bookmark is selected, it opens a `netrw` buffer of the folder, and does not `:cd` into it and restore a `Session.py` like it used to.

Currently running Vim 7.4 with patches 1-1795.

Let me know if there's anything I can do to help debug this.

**Comment by mhinz** [comment]
Hi,

sorry for the late response, but I was away from computers for some time.

Please pull the latest changes, it should be fixed now.

**Comment by mhinz** [comment]
All my manual tests were working, so I close this. Please reopen, if it isn't fixed for you!

**Comment by amadeus** [comment]
Hmm, still appears to not be working for me, despite the updates?

I am running MacVim 7.4 patches 1-1849.

Here are my Startify configuration settings:

```
" Startify bookmarks are now customizeable
if filereadable(expand('$HOME/.vim/misc/bookmarks.vim'))
  source $HOME/.vim/misc/bookmarks.vim
endif

let g:startify_custom_header = [
  \ '                                ______',
  \ '            __                /\  ____`\',
  \ '   __   __ /\_\    ___ ___    \ \ \___\ \',
  \ '  /\ \ /\ \\/\ \ /` __` __`\   \ \  ____ \',
  \ '  \ \ \_/ / \ \ \/\ \/\ \/\ \   \ \ \___\ \',
  \ '   \ \___/   \ \_\ \_\ \_\ \_\   \ \_______\',
  \ '    \/__/     \/_/\/_/\/_/\/_/    \/_______/',
  \ '',
  \ '  ===========================================',
  \ '',
  \ ]

let g:startify_custom_footer = [
  \ '',
  \ '  ===========================================',
  \ '',
  \ '  Copyright Tubez, 2016'
  \ ]

let g:NERDTreeHijackNetrw = 0
let g:startify_session_autoload = 1
let g:startify_change_to_dir = 1
let g:ctrlp_reuse_window = 'startify'
let g:startify_list_order = ['bookmarks', 'files']
let g:startify_change_to_dir = 1

let g:startify_skiplist = [
  \ 'COMMIT_EDITMSG',
  \ $VIMRUNTIME .'/doc',
  \ 'bundle/.*/doc',
  \ '\.DS_Store'
  \ ]

let g:startify_session_autoload = 1
let g:startify_session_dir = '.'
```

**Comment by mhinz** [comment]
What's the content of `g:startify_bookmarks` and does the bookmarked directory contain a `Session.vim`?

**Comment by mhinz** [comment]
Okay, I successfully tested with MacVim, too.

First of all, setting `g:startify_session_dir` to `'.'` means that Startify considers _every_ file in the current directory a Vim session file. That's probably not what you want. (But it works even with that setting for me.)

Please add `'/tmp` to your `g:startify_bookmarks` and try this:

1. `$ cd /tmp`
1. `$ mvim foo`
1. `:SS foo`
1. `:x`
1. `$ cd`
1. `$ mvim`

Now, selecting bookmark "/tmp" should source `/tmp/Session.vim` automatically and open the only buffer of the session for `/tmp/foo`.

**Comment by amadeus** [comment]
Nevermind, it's actually working. Thanks!
