### ISSUE TITLE
Footer doesn't seem to support the same features as header

### ISSUE THREAD

**Issue by amadeus** [mhinz/vim-startify#316]
I was messing around with some of the new quote stuff, and I tried putting it into the footer as per the example (in combining it with an `g:ascii`) but it just ended up outputting this string literally:

```
let g:ascii = [
      \ '        __',
      \ '.--.--.|__|.--------.',
      \ '|  |  ||  ||        |',
      \ ' \___/ |__||__|__|__|',
      \ ''
      \]

let g:startify_custom_footer = 'map(startify#fortune#boxed() + g:ascii, "\"   \".v:val")'
```

**Comment by mhinz** [comment]
Hah, right. It only takes lists and no strings that evaluate to lists at the moment.

Will fix this this evening!

**Comment by mhinz** [comment]
Should work now!

**Comment by amadeus** [comment]
It appears to still have some issues?

![example](http://wtf.amadeus.wtf/monosnap/_2018-04-26_20-16-34.png)

**Comment by mhinz** [comment]
Huh.. that doesn't happen for me.

It looks like the syntax files favours `:hi StartifyBracket` over `:hi StartifyFooter` for the footer.

Could you list _all_ your Startify options?

**Comment by mhinz** [comment]
Woah.. when you put `" let g:startify_fortune_use_unicode = 1` in your vimrc.. does it work?

**Comment by amadeus** [comment]
![example](http://wtf.amadeus.wtf/monosnap/_2018-04-27_01-29-17.png)

Oh dang, what is this sorcery?!

**Comment by mhinz** [comment]
That's very weird indeed. The only difference is the box-drawing characters used: https://github.com/mhinz/vim-startify/blob/c1a81780d5a7cc79f1d69f91b8ab09f1b8c2c925/autoload/startify/fortune.vim#L72-L79

So, somehow [regexp](https://github.com/mhinz/vim-startify/blob/c1a81780d5a7cc79f1d69f91b8ab09f1b8c2c925/syntax/startify.vim#L34) doesn't seem to be matching, although it doesn't match particular types of characters, but simply a range of lines (from `startify#get_lastline()` to the end of the buffer).

I have to think about that. :P

**Comment by mhinz** [comment]
I'm an idiot. It _never_ worked! Or only by accident. It simply stopped at the first `*` character. (You can see in your screenshot that the upper left corner of the box is colored differently.)

Anyway, now it should really match _any_ character to the end of the buffer.

**Comment by amadeus** [comment]
Oh awesome, works great! Although the unicode version was cooler, so I'll probably stick with that.

Thanks for taking the time!
